// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6iShifolUst6a_MJGARyNtKOutkQv7rk',
    appId: '1:473546218661:web:160096a6509633ac55414c',
    messagingSenderId: '473546218661',
    projectId: 'fudbd-6bec5',
    authDomain: 'fudbd-6bec5.firebaseapp.com',
    storageBucket: 'fudbd-6bec5.appspot.com',
    measurementId: 'G-N5TF9D9DCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRbQ5qmIy0vpwCayydaE5goDEcQOXua9s',
    appId: '1:473546218661:android:57b9a346875f757855414c',
    messagingSenderId: '473546218661',
    projectId: 'fudbd-6bec5',
    storageBucket: 'fudbd-6bec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxUywhS193OMZ59So_MuUie0gFsCyOyoQ',
    appId: '1:473546218661:ios:7474841727063c6655414c',
    messagingSenderId: '473546218661',
    projectId: 'fudbd-6bec5',
    storageBucket: 'fudbd-6bec5.appspot.com',
    iosBundleId: 'com.example.fud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxUywhS193OMZ59So_MuUie0gFsCyOyoQ',
    appId: '1:473546218661:ios:a61d5e9e7fa86d5455414c',
    messagingSenderId: '473546218661',
    projectId: 'fudbd-6bec5',
    storageBucket: 'fudbd-6bec5.appspot.com',
    iosBundleId: 'com.example.fud.RunnerTests',
  );
}
