// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-jzkWKFHOwLWrVRwAqeAPh__dZLrvic',
    appId: '1:310529725079:web:f7d7ef3fee7a1f01e84fd2',
    messagingSenderId: '310529725079',
    projectId: 'fud-moviles',
    authDomain: 'fud-moviles.firebaseapp.com',
    storageBucket: 'fud-moviles.appspot.com',
    measurementId: 'G-C2G1E23Y38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYqL3IumkTqhffQInSs2Wkz5qeGx5tF84',
    appId: '1:310529725079:android:c5b6d034c578bb98e84fd2',
    messagingSenderId: '310529725079',
    projectId: 'fud-moviles',
    storageBucket: 'fud-moviles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMfLQFikO1pREiX9ywlvfpQEPr3IxaDOU',
    appId: '1:310529725079:ios:c4f29d0573736f00e84fd2',
    messagingSenderId: '310529725079',
    projectId: 'fud-moviles',
    storageBucket: 'fud-moviles.appspot.com',
    iosBundleId: 'com.example.fud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMfLQFikO1pREiX9ywlvfpQEPr3IxaDOU',
    appId: '1:310529725079:ios:84221c4e7920e04fe84fd2',
    messagingSenderId: '310529725079',
    projectId: 'fud-moviles',
    storageBucket: 'fud-moviles.appspot.com',
    iosBundleId: 'com.example.fud.RunnerTests',
  );
}
